services:
  greetings-service:
    image: greetings-app:0.0.1
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      # Required by buildpack.
      - OTEL_JAVAAGENT_ENABLED=true
      - OTEL_METRIC_EXPORT_INTERVAL=15000
       # If using buildpack it disables metrics and logs. We want metrics, so we need to explicitly enable them
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_SERVICE_NAME=greetings-app

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    command:
      --config=/etc/otel-collector-config.yml
    ports:
      - "4317:4317"
      - "4318:4318"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  init:
    image: &tempoImage grafana/tempo:latest
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ./tempo-data:/var/tempo

  tempo:
    image: *tempoImage
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/var/tempo
    ports:
      - "3200" # tempo.
      - "4317" # otlp grpc
    depends_on:
      - init



  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000"      
