receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:9464"
  otlp:
    endpoint:
      tempo:4317
    tls:
      insecure: true
service:
  pipelines:
    metrics:
      exporters:
        - prometheus
      processors:
        - batch
      receivers:
        - otlp
    traces:
      exporters:
        - otlp
        - debug
      processors:
        - batch
      receivers:
        - otlp
        - otlp
    logs:
      exporters:
        - debug
      processors:
        - batch
      receivers:
        - otlp
